FROM docker.io/envoyproxy/envoy-build@sha256:20656853fae51927cda557e7af80ccff175f5de6f84bd0f092cd8672b2a6e0fe

ARG USERNAME=envoybuild

ENV DEBIAN_FRONTEND=noninteractive

# 基础工具
RUN apt-get -y update \
  && apt-get -y install --no-install-recommends \
     python3 net-tools iputils-ping procps psmisc \
     vim openssh-client aspell sudo \
  && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y clangd clang llvm \
  && rm -rf /var/lib/apt/lists/*

# 确保 home 存在 & 可写（关键）
RUN mkdir -p /home/${USERNAME} \
  && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}

# sudo（可选）
RUN echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
  && chmod 0440 /etc/sudoers.d/${USERNAME}

# 切用户（但不改 HOME）
USER ${USERNAME}
WORKDIR /build

ENV DEBIAN_FRONTEND=